defaults:
  - /dataset/tiled_filtered/level2_extent224@_here_
  - _self_

mlflow_uris:
  embeddings:
    train: mlflow-artifacts:/111/641017e995c6406ca0c5386c08d1aa0d/artifacts/embeddings/train
    test_preliminary: mlflow-artifacts:/111/641017e995c6406ca0c5386c08d1aa0d/artifacts/embeddings/test_preliminary
    test_final: mlflow-artifacts:/111/641017e995c6406ca0c5386c08d1aa0d/artifacts/embeddings/test_final
