defaults:
  - /dataset/tiled_filtered/level2_extent224@_here_
  - _self_

mlflow_uris:
  embeddings:
    train: mlflow-artifacts:/1/e3486996e53a416c955d45db9ae7f1d7/artifacts/embeddings/train
    test_preliminary: mlflow-artifacts:/1/e3486996e53a416c955d45db9ae7f1d7/artifacts/embeddings/test_preliminary
    test_final: mlflow-artifacts:/1/e3486996e53a416c955d45db9ae7f1d7/artifacts/embeddings/test_final
