defaults:
  - /dataset/tiled_filtered/level1_extent224@_here_
  - _self_

mlflow_uris:
  embeddings: 
    train: mlflow-artifacts:/111/744c6cfe294a44a0b3a031a08b20d5b3/artifacts/embeddings/train
    test_preliminary: mlflow-artifacts:/111/744c6cfe294a44a0b3a031a08b20d5b3/artifacts/embeddings/test_preliminary
    test_final: mlflow-artifacts:/111/744c6cfe294a44a0b3a031a08b20d5b3/artifacts/embeddings/test_final
