# @package _global_

downscale: 9  # from 0.5 mpp to 4.5 mpp
max_concurrent: 4
mlflow_artifact_path: "epithelium"

metadata:
  run_name: "Epithelium masks Downscale"
  description: "Downscale epithelium masks for dysplasia project"