# @package _global_

token: ${oc.env:HF_TOKEN,null}
model: virchow2
level: 2

tiling_uris: 
 - mlflow-artifacts:/1/26885cb72d9f4950b541dac8bc3ca1cf/artifacts/filtered_tiles/train
 - mlflow-artifacts:/1/26885cb72d9f4950b541dac8bc3ca1cf/artifacts/filtered_tiles/test_preliminary
 - mlflow-artifacts:/1/26885cb72d9f4950b541dac8bc3ca1cf/artifacts/filtered_tiles/test_final

output_dir: ${project_path}/embeddings

skip_existing: True

dataloader:
  batch_size: 192
  num_workers: 0
  persistent_workers: False

metadata:
  experiment_name: Ulcerative Colitis Dysplasia
  run_name: '📂 Tile Embeddings'
  description: 'Ulcerative Colitis Dysplasia Tile Embeddings' 
  user: jiribuchta
