# @package _global_

mlflow_artifact_path: "epi_segmentation"

splits:
  - train
  - test_preliminary
  - test_final

model_name: "episeg-1"
request_timeout: 100
max_concurrent: 4
max_slide_concurrency: 2
mask_threshold: 0.5

metadata:
  run_name: "🧫 Epi Segmentation"
  description: "Segment epithelium masks for all tiles using episeg-1"
