# @package _global_

mpp: ???
tile_extent: ???
stride: ???
tissue_threshold: 0.5
mlflow_artifact_path: tiling
target_groups:
  - "LG Dysplasia"
  - "HG Dysplasia"

metadata:
  run_name: 🧩 Tiling - 1024px @ 1.55mpp
  description: "Create tiles for dysplasia project"