defaults:
  - /dataset/tiled/level2_extent512@_here_
  - _self_

mlflow_uris:
  tiling_filtered: 
    train: mlflow-artifacts:/1/70f252b15284442abcc475a87d548e72/artifacts/filtered_tiles/train
    test_preliminary: mlflow-artifacts:/1/70f252b15284442abcc475a87d548e72/artifacts/filtered_tiles/test_preliminary
    test_final: mlflow-artifacts:/1/70f252b15284442abcc475a87d548e72/artifacts/filtered_tiles/test_final