defaults:
  - /dataset/tiled/level2_extent224@_here_
  - /dataset/stats@_here_
  - /dataset/thresholds@_here_
  - _self_

mlflow_uris:
  tiling_filtered:
    train: mlflow-artifacts:/1/d06ba1965fb549759035ab8f7ddd65e3/artifacts/embeddings/train
    test_preliminary: mlflow-artifacts:/1/d06ba1965fb549759035ab8f7ddd65e3/artifacts/embeddings/test_preliminary
    test_final: mlflow-artifacts:/1/d06ba1965fb549759035ab8f7ddd65e3/artifacts/embeddings/test_final
