defaults:
  - /dataset/tiled/level2_extent224@_here_
  - _self_

mlflow_uris:
  tiling_filtered: 
    train: mlflow-artifacts:/111/8928f53d7b65474283b5262737fc1531/artifacts/filtered_tiles/train
    test_preliminary: mlflow-artifacts:/111/8928f53d7b65474283b5262737fc1531/artifacts/filtered_tiles/test_preliminary
    test_final: mlflow-artifacts:/111/8928f53d7b65474283b5262737fc1531/artifacts/filtered_tiles/test_final