defaults:
  - /dataset/tiled/level1_extent224@_here_
  - _self_

mlflow_uris:
  tiling_filtered: 
    train: mlflow-artifacts:/111/ffc7118d80164779bc75ef14dbd2943b/artifacts/filtered_tiles/train
    test_preliminary: mlflow-artifacts:/111/ffc7118d80164779bc75ef14dbd2943b/artifacts/filtered_tiles/test_preliminary
    test_final: mlflow-artifacts:/111/ffc7118d80164779bc75ef14dbd2943b/artifacts/filtered_tiles/test_final