# @package _global_

# defaults:
#   - /dataset/processed_w_tiling@_here_
#   - _self_

dataset:
  name: dysplasia_embeddings
  mlflow_uris:
    train: mlflow-artifacts:/111/bc3c85b1f4774d8d97bb15dd20f95838/artifacts/filtered_tiles/train
    test_preliminary: mlflow-artifacts:/111/bc3c85b1f4774d8d97bb15dd20f95838/artifacts/filtered_tiles/test_preliminary
    test_final: mlflow-artifacts:/111/bc3c85b1f4774d8d97bb15dd20f95838/artifacts/filtered_tiles/test_final
  embeddings:
    dir: ${project_path}/embeddings
    model: prov-gigapath
  target_groups:
    - "LG Dysplasia"
    - "HG Dysplasia"
  label_mode: percentages
  label_scale: null
  clamp_labels: true

embedd_model: prov-gigapath
embedd_path: ${project_path}/embeddings/${embedd_model}


data:
  _target_: dysplasia.data.DataModule
  batch_size: 128
  num_workers: 4
  datasets:
    train:
      _target_: dysplasia.data.DysplasiaEmbeddingsDataset
      uri: ${dataset.mlflow_uris.train}
      embeddings_dir: ${dataset.embeddings.dir}/${dataset.embeddings.model}
      target_labels: ${dataset.target_groups}
      label_mode: ${dataset.label_mode}
      label_scale: ${dataset.label_scale}
      clamp_labels: ${dataset.clamp_labels}
    val:
      _target_: dysplasia.data.DysplasiaEmbeddingsDataset
      uri: ${dataset.mlflow_uris.test_preliminary}
      embeddings_dir: ${dataset.embeddings.dir}/${dataset.embeddings.model}
      target_labels: ${dataset.target_groups}
      label_mode: ${dataset.label_mode}
      label_scale: ${dataset.label_scale}
      clamp_labels: ${dataset.clamp_labels}
    test:
      _target_: dysplasia.data.DysplasiaEmbeddingsDataset
      uri: ${dataset.mlflow_uris.test_final}
      embeddings_dir: ${dataset.embeddings.dir}/${dataset.embeddings.model}
      target_labels: ${dataset.target_groups}
      label_mode: ${dataset.label_mode}
      label_scale: ${dataset.label_scale}
      clamp_labels: ${dataset.clamp_labels}
