annot_path: ${data_path}/annotations
selected_clear_cases: ${data_path}/IBD_dysplazie_jasne.xlsx
selected_unclear_cases: ${data_path}/IBD_dyspl_nejasne.xlsx
regex_pattern: '^\d+_\d+_HE_[0-9A-Z]+\.(czi|json)$'
