annot_path: /mnt/data/IKEM/colon/IBD_AI/dysplasia/annotations
selected_clear_cases: /mnt/data/IKEM/colon/IBD_AI/dysplasia/IBD_dysplazie_jasne.xlsx
selected_unclear_cases: /mnt/data/IKEM/colon/IBD_AI/dysplasia/IBD_dyspl_nejasne.xlsx
regex_pattern: '^\d+_\d+_HE_[0-9A-Z]+\.(czi|json)$'
