# @package _global_

defaults:
  - /ml
  - _self_

mode: fit
label_mode: high_low
val_fold: ???

mean: ${dataset.mean}
std: ${dataset.std}
thresholds: ${dataset.thresholds}

trainer:
  enable_checkpointing: true
  max_epochs: 50
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min 
      patience: 5

model:
  lr: 1e-4
  out_features: 2
