defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 1.55
tile_extent: 512
stride: 256

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/1/b9d1dbec7a3146f6811e8b32bd91bb5c/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/1/b9d1dbec7a3146f6811e8b32bd91bb5c/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/1/b9d1dbec7a3146f6811e8b32bd91bb5c/artifacts/tiling/test_final
