defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 0.52
tile_extent: 224
stride: 112
epithelium_threshold: 0.34

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/111/fc9830fbb6e04e94960532ba58534714/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/111/fc9830fbb6e04e94960532ba58534714/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/111/fc9830fbb6e04e94960532ba58534714/artifacts/tiling/test_final