defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 1.55
tile_extent: 224
stride: 112
epithelium_threshold: 0.14

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/111/f1b49bb8a3c64e7182659cec3f323276/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/111/f1b49bb8a3c64e7182659cec3f323276/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/111/f1b49bb8a3c64e7182659cec3f323276/artifacts/tiling/test_final