defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 0.52
tile_extent: 224
stride: 112

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/111/687ff6a6f0e84b6a83e74233bdba31ce/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/111/687ff6a6f0e84b6a83e74233bdba31ce/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/111/687ff6a6f0e84b6a83e74233bdba31ce/artifacts/tiling/test_final