defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 1.55
tile_extent: 512
stride: 256

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/1/348861913aac4be3a07a54a8e96de96a/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/1/348861913aac4be3a07a54a8e96de96a/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/1/348861913aac4be3a07a54a8e96de96a/artifacts/tiling/test_final
