defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 1.55
tile_extent: 224
stride: 112

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/111/fb279f0d3c174c4990b58a48735003be/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/111/fb279f0d3c174c4990b58a48735003be/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/111/fb279f0d3c174c4990b58a48735003be/artifacts/tiling/test_final