defaults:
  - /dataset/processed_w_masks@_here_
  - _self_

mpp: 0.52
tile_extent: 224
stride: 112

mlflow_uris:
  tiling: 
    train: mlflow-artifacts:/111/4654b43a26684b3cb32fcdc9d22934b3/artifacts/tiling/train
    test_preliminary: mlflow-artifacts:/111/4654b43a26684b3cb32fcdc9d22934b3/artifacts/tiling/test_preliminary
    test_final: mlflow-artifacts:/111/4654b43a26684b3cb32fcdc9d22934b3/artifacts/tiling/test_final